### ISSUE TITLE
Maximum Map Zoom Level

### ISSUE THREAD

**Issue by nirabpudasaini** [GeoODK/collect#11]
I know that many map tile provider do not give higher zoom levels and also the file size gets much bigger with .mbtiles. But for many application it would be very hard to draw polygons on tablets and almost impossible on many phones. 

One possible solution might be to use mapsforge library and using the .map files which are considerably smaller in size to render offline maps. This will allow higher zoom levels. 

Another solution might be allowing users to change the maximum zoom level for their offline map data.

**Comment by mraminemx** [comment]
Hi, can you please share with us more information about the mapsforge solution to solve the zooming problem.
think's.

**Comment by nirabpudasaini** [comment]
mapsforge is a library that uses binary data to generate map tiles on the fly. This means that unlike storing individual tiles (like with mbtiles) it would allow higher zoom levels without the exponential increase in file size. .

**Comment by jnordling** [comment]
Ok so just resolved the zoom level limitation by standing up TileServer just for GeoODK that are dedicated to the app. The issue really before was that the app linked to the OSM servers and they limit the XYZTileSouce zoom. I have set the max zoom of the new TileSource to 22. Will the satisfy the zoom level limitations? If not i can increase, just need to know if it is necessary.

I have also added a few other base map options and more coming, 

The updates will be added during the September Release, but if your interested in checking it out you can find the changes on the devops branch of the Github account.


Jon

**Comment by nirabpudasaini** [comment]
Well that only partly solves the issue. Imagine creating tiles for zoom level 22. I think even for a small area that will require lots of storage. I still think in device rendering would be very much helpful addition and can be easily done with mapsforge. 

You can close this issue and maybe open another, In device map rendering as a feature request.
