### ISSUE TITLE
Issues with editing geoshape

### ISSUE THREAD

**Issue by nirabpudasaini** [GeoODK/collect#13]
I have found that in some survey being able to save a single point with geoshape, instead of geopoint is very useful. But if you do not have a complete polygon you get issues while editing the geoshape feature. 

I am working with the version available on google play store. When i record geoshape i can save the geoshape even when i have 1,2,3 points. When i later edit the geoshape with (1/2/3 points only) the app behaves in a strange way. It deletes one point and says cannot create polygon with less than three points. It also stops addition of points and you cannot edit the existing points. In case there was previously only a single point the app crashes.

**Comment by thanhgis** [comment]
Hi Jon, 

This problem is still exist with the latest version of GeoODK on Google Play Store, and with GitHub's master and devops branches aslo. 

Can you have a look at it?

**Comment by jnordling** [comment]
The Google Play build has now been updated .Im going to close this ticket. This has been resolved.
