### ISSUE TITLE
Update the geopoint widget and activity update

### ISSUE THREAD

**Issue by GeoODK** [GeoODK/collect#14]
When collecting a survey and collecting a geopoint, there is no map functionality to view, update or alter the point on the map before saving. Currently you can only view the geopoint on the "Map Data" section of the application.

**Comment by MohammedHabboub** [comment]
Good news, this is exactly what I need. However, I've uploaded the xform (which contains the "geopoint" data type) to the online converter, but is still there is no map functionality to view, update or alter the point on the map before saving. is there anything that I should do to view the geopoint on a map?

**Comment by jnordling** [comment]
Please check out the latest release, this is now build into the core functionality 


Thanks for your contributions. 

Jon
