### ISSUE TITLE
Problem Importing to Android Studio

### ISSUE THREAD

**Issue by nirabpudasaini** [GeoODK/collect#15]
It can be easily imported to gradel build but the project.properties and default.properties might cause errors. These file can be deleted before import to successfully import the project.

Since the files are auto generated by android tools , i think it can be added to the .gitignore.

**Comment by GeoODK** [comment]
Thanks Ill add this to the .gitignore

**Comment by GeoODK** [comment]
I am getting ready to migrate the code over to Android Studio on the github repo. Just wanted to let you know i added the https://github.com/GeoODK/collect/blob/master/.gitignore files you seggested. I will do the same for the Studio.
