### ISSUE TITLE
Can't find line data with Geotrace & Geoshape

### ISSUE THREAD

**Issue by olabodeolushi** [GeoODK/collect#16]
Hi,

I tried using the geotrace and geoshape, it seemed to work fine when i collect the data and i can find the coordinates in the rows in Aggregate server but it doesn't show when i try to visualize the map. Am i doing anything wrong? I also exported to fusion tables, but I can't seem to get the line and polygon data to show. My point data shows fine.

Would appreciate your help

**Comment by jnordling** [comment]
When a geoshape and geotrace field is completed in a form it is stored as structured string of points seperated by semi-coline. Then once that data is submitted to the server the web application the has different ways of visualizing the data. If your using ODK Aggregate they do not yet have a way to view the geoshape or geotrace data. However if your using something like ona.io, I believe they have support for this.

If your also just trying to make a we map and need at shapefile to view in arcgis or someother gis you can use the web geocoverter. Check out the blog on it
http://blog.geoodk.com/posts/convert-geoshape-geotrace-geopoint-to-shapefile

Hope this helps,
Jon

**Comment by jnordling** [comment]
All GeoObjects are now rendered in the mapView
