### ISSUE TITLE
Images are not scaled according to pixel density of the device

### ISSUE THREAD

**Issue by karner** [GeoODK/collect#18]
When including images in forms, the size of the image in the app is influenced by the pixel density of the device while the fonts are not. For example: an image with 70x50px might be 10x7 mm on the screen of a Samsung Galaxy S2, but only 3*2 mm on the LG G3

**Comment by jnordling** [comment]
The size of the text can be scaled down in the General Settings page.

**Comment by karner** [comment]
So it also can't be read? :-P No, the issue is the image - but I guess this is an odk-issue and not directly caused by geoodk-code...
