### ISSUE TITLE
[Feature] Show Grouped Inputs on one screen

### ISSUE THREAD

**Issue by amenk** [GeoODK/collect#19]
Can we show grouped inputs on one screen?

If you have any hints I would appreciate this. I might want to create a pull request, but I am not that experienced with Android development.

**Comment by jnordling** [comment]
What type of grouped content, can you post a form so I can check this out.

Jon

**Comment by amenk** [comment]
Don't have a sample ATM. But I am talking about the `begin group` and `end group` tags: http://xlsform.org/#grouping

**Comment by jnordling** [comment]
Now there is a custom GeoRender object that finds all geo features in a form and will render them. Test it out. Its in the devops branch
