### ISSUE TITLE
[Feature] Geo Input via OpenStreetMap Features

### ISSUE THREAD

**Issue by amenk** [GeoODK/collect#24]
It should be possible to select an OSM feature on the map as current position and to link the form with that OpenStreetMap feature.

* I am not sure how to preload the OSM data. One possibility would be some kind of .csv file with lat / lon / name. Another option would be to use the UTFgrid functionality that can be embedded into .mbtiles files

* Also the form would need a new data type "OSM feature ID" or something like that. Or we could directly write it into the position file like "node 123456" instead of "lat lon height accuracy"

**Comment by hallahan** [comment]
Check out [OpenMapKit](https://github.com/americanredcross/openmapkit/)

**Comment by amenk** [comment]
Interesting. WIll definitely have a look. What I don't like at first glance is, that a second app has to be started.

**Comment by jnordling** [comment]
Im going to close this tickets, we can move this discussion to https://groups.google.com/forum/#!forum/geoodk-community is we want to continue.

Thanks for your feed back, please check out the latest release in the App Store.

Jon
