### ISSUE TITLE
External select causing error

### ISSUE THREAD

**Issue by karner** [GeoODK/collect#32]
Using an external select (http://xlsform.org/#external) causes an error: "Couldn't read row 0, col -1 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it."

Happened with the example form available at https://docs.google.com/spreadsheets/d/12qZL34kuHSZGWDv0BBJ1qf7dSmml-d2VnMWH0Vtg-O4/edit#gid=683809272

However you have to build this form using Nafundi's XLSForm Converter (https://gumroad.com/l/xlsform-offline) the online converter and the XLSForm offline converter from the GeoODK website both don't create the csv-file with the external select options, the offline tool doesn't even create the xml file.

![screenshot_2015-10-14-11-08-05](https://cloud.githubusercontent.com/assets/5310696/10481993/d9e31e42-7274-11e5-838c-a688b0027e66.png)

**Comment by jnordling** [comment]
Can you provide all files so that i can replicate on my end?

**Comment by karner** [comment]
Sorry - of course. You can find the files here: https://www.dropbox.com/sh/q3op8x61snf6jx7/AADx6bhAbMurpZJtEaGDgPuma?dl=0

The zip archive contains the form and the external options in the csv - should work by copying the contents of the zip to the forms folder on the phone. I also put the xlsForm in the folder in case you want to give it a look.

**Comment by jnordling** [comment]
Cool ill take a look.

**Comment by jnordling** [comment]
I was able to load the form into GeoODK just fine, im using the devops branch as the build, which build are you using?

**Comment by karner** [comment]
I used the app build from the play store

**Comment by jnordling** [comment]
Can you test this with the new version of GeoODK and let me know if this problem persists. 

Jon

**Comment by jkpr** [comment]
I just ran into this problem and then solved it. The problem occurred was because the form had multiple languages and the current language was not in the external_choices tab, i.e. while I had a column label::English, there was no label::Indonesian column in the external choices, and Indonesian was the form's default language. I would guess _that_ is what the column -1 means in the error message (the app can't find the correct column).
